project_id = "eoodkccjwyybwgmkzarx"

[functions.generate-decisions]
verify_jwt = false

[functions.analyze-product-speech]
verify_jwt = false

[functions.match-product-from-speech]
verify_jwt = false

[functions.voice-to-enhanced-text]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.search-exposure]
verify_jwt = false

[functions.import-products-csv]
verify_jwt = false

[functions.edit-product-with-ai]
verify_jwt = false
